name: Vellore School of AI
description: Our mission is to solve humanity's challenging problems using AI.
avatar: /images/logo.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: https://github.com/vlrsoai
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: jekyllrb
  stackoverflow:
  youtube:
  googleplus:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:
google_analytics: UA-93019594-2
url: https://vlrsoai.github.io/
baseurl: ""
permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
